import React, { useState } from 'react';
import type { Lookbook, LookbookItem } from '../types';
import { BackIcon } from '../components/icons';

interface CreateLookbookProps {
  addLookbook: (lookbook: Omit<Lookbook, 'id' | 'createdAt'>) => Promise<void>;
  navigate: (view: string) => void;
}

const CreateLookbook: React.FC<CreateLookbookProps> = ({ addLookbook, navigate }) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [items, setItems] = useState<Omit<LookbookItem, 'id'>[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setIsLoading(true);
      const files = Array.from(e.target.files);
      const newItemsPromises = files.map(file => {
        return new Promise<Omit<LookbookItem, 'id'>>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = (event) => {
            resolve({
              imageUrl: event.target?.result as string,
              name: '',
              price: '',
            });
          };
          reader.onerror = reject;
          reader.readAsDataURL(file);
        });
      });
      const newItems = await Promise.all(newItemsPromises);
      setItems(prev => [...prev, ...newItems]);
      setIsLoading(false);
    }
  };

  const updateItem = (index: number, field: 'name' | 'price', value: string) => {
    const newItems = [...items];
    newItems[index] = { ...newItems[index], [field]: value };
    setItems(newItems);
  };
  
  const removeItem = (index: number) => {
    setItems(prev => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title || items.length === 0) {
        alert("Por favor, adicione um título e pelo menos uma imagem.");
        return;
    }
    await addLookbook({ title, description, items: items.map(item => ({...item, id: ''})) }); // ID will be generated by backend
    navigate('dashboard');
  };

  return (
    <div>
      <div className="flex items-center mb-6">
        <button onClick={() => navigate('dashboard')} className="p-2 rounded-full hover:bg-gray-200 mr-4">
          <BackIcon />
        </button>
        <h1 className="text-3xl font-bold text-gray-800">Criar Novo Lookbook</h1>
      </div>

      <form onSubmit={handleSubmit} className="space-y-8">
        <div className="bg-white p-8 rounded-xl shadow-lg">
          <h2 className="text-xl font-bold text-gray-800 mb-4">Detalhes do Lookbook</h2>
          <div className="space-y-4">
            <div>
              <label htmlFor="title" className="block text-gray-700 font-semibold mb-2">Título</label>
              <input type="text" id="title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Ex: Nova Coleção Dior" className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-teal-green" required />
            </div>
            <div>
              <label htmlFor="description" className="block text-gray-700 font-semibold mb-2">Descrição (Opcional)</label>
              <textarea id="description" value={description} onChange={(e) => setDescription(e.target.value)} rows={3} placeholder="Ex: Peças exclusivas para a primavera" className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-teal-green"></textarea>
            </div>
          </div>
        </div>

        <div className="bg-white p-8 rounded-xl shadow-lg">
            <h2 className="text-xl font-bold text-gray-800 mb-4">Itens do Lookbook</h2>
            <div>
              <label htmlFor="image-upload" className="w-full cursor-pointer bg-brand-light-gray border-2 border-dashed border-gray-300 rounded-lg flex flex-col items-center justify-center p-6 text-center hover:bg-gray-100 transition-colors">
                <span className="text-brand-teal-green font-semibold">Clique para carregar as imagens</span>
                <span className="text-sm text-gray-500 mt-1">PNG, JPG, GIF até 10MB</span>
                <input id="image-upload" type="file" multiple accept="image/*" className="hidden" onChange={handleFileChange} />
              </label>
              {isLoading && <p className="text-center mt-4">Carregando imagens...</p>}
            </div>
            
            <div className="mt-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {items.map((item, index) => (
                    <div key={index} className="border rounded-lg p-4 space-y-3 relative">
                        <button type="button" onClick={() => removeItem(index)} className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center font-bold">&times;</button>
                        <img src={item.imageUrl} alt="preview" className="w-full h-40 object-cover rounded-md"/>
                        <input type="text" placeholder="Nome do item" value={item.name} onChange={(e) => updateItem(index, 'name', e.target.value)} className="w-full text-sm px-2 py-1 border border-gray-300 rounded-md" />
                        <input type="text" placeholder="Preço (opcional)" value={item.price} onChange={(e) => updateItem(index, 'price', e.target.value)} className="w-full text-sm px-2 py-1 border border-gray-300 rounded-md" />
                    </div>
                ))}
            </div>
        </div>

        <div className="flex justify-end">
          <button type="submit" className="bg-brand-teal-green text-white px-6 py-3 rounded-lg font-semibold hover:bg-brand-dark-green transition-colors disabled:bg-gray-400" disabled={isLoading}>
            Salvar Lookbook
          </button>
        </div>
      </form>
    </div>
  );
};

export default CreateLookbook;
